[package]
name = "tuc"
description = "When cut doesn't cut it"
version = "0.1.0"
authors = ["Riccardo Attilio Galli <riccardo@sideralis.org>"]
edition = "2018"
repository = "https://github.com/riquito/tuc"
license = "GPL-3.0-or-later"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.14"
anyhow = "1.0.31"
regex = "1.3.7"
