[package]
name = "tuc"
description = "When cut doesn't cut it"
version = "0.4.0"
authors = ["Riccardo Attilio Galli <riccardo@sideralis.org>"]
edition = "2018"
homepage = "https://github.com/riquito/tuc"
repository = "https://github.com/riquito/tuc"
license = "GPL-3.0-or-later"
readme = "README.md"
keywords = ["cli"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.14"
anyhow = "1.0.31"
regex = "1.3.7"
grep-cli = "0.1.5"
termcolor = "1.1.2"

[dev-dependencies]
assert_cmd = "1.0.1"
