name: Build, bump tag version and release

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - master

jobs:
  check-if-needs-release:
    name: Check if needs release
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.is-new-version.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Check
        run: cargo check --locked

      - name: Get version from Cargo.toml
        id: version-by-cargo
        run: |
          echo "::set-output name=version::v$(cargo metadata --offline --no-deps --format-version=1 | jq --raw-output '.packages[0].version')"

      - name: Is already tagged at latest version?
        id: is-new-version
        run: |
          echo "::set-output name=result::$(test $(git tag --list ${{ steps.version-by-cargo.outputs.version }}) && echo "" || echo ${{ steps.version-by-cargo.outputs.version }})"

      - name: Push tag/create release point
        id: apply-tag
        if: steps.is-new-version.outputs.result != ''
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ steps.is-new-version.outputs.result }}

  release:
    needs: check-if-needs-release
    if: needs.check-if-needs-release.outputs.new_version != ''
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: tuc
            asset_name: tuc-linux-amd64
          - os: macos-latest
            artifact_name: tuc
            asset_name: tuc-macos-amd64
          - os: windows-latest
            artifact_name: tuc.exe
            asset_name: tuc-windows-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Build project
        run: cargo build --release --locked

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ needs.check-if-needs-release.outputs.new_version }}
          overwrite: true
